# Konfigurationsformat
# columns: Liste von Spalten, die in der Tabelle vorkommen
# column: Label der Spalte für das Ergebnis
### name oder index müssen angegeben werden, um die Spalte zu identifizieren
# name: Name der Spalte in der Tabelle
# index: Index der Spalte in der Tabelle
###
# name ist der Name der Spalte in der Tabelle: zb: Versanddatum
# index ist die Spaltennummer der Reihe: zb:
# Spalte AB = 28
# Spalte AZ = 52
# suffix: Suffix, das an den Wert der Spalte angehängt wird: zb: €
# prefix: Präfix, das an den Wert der Spalte angehängt wird: zb: €
columns:
 - column: "Datum"
   name: "Versanddatum"
 - column: "Trackingnummer"
   index: 5
 - column: "Empfänger"
   index: 41
 - column: "Kosten"
   name: "Ausgehandelter Gesamtbetrag"
   suffix: " €"
