# Für weitere Hilfe: https://github.com/ur-wesley/csvParser
columns:
 - column: "Datum"
   name: "Versanddatum"
 - column: "Trackingnummer"
   index: 5
 - column: "Empfänger"
   index: 41
 - column: "Kosten"
   name: "Ausgehandelter Gesamtbetrag"
   suffix: "€"
   replace:
    ".": ","
