name: Build and Zip Go App (Windows)

on:
 workflow_dispatch:
 release:
  types: [created]

jobs:
 build:
  runs-on: windows-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Go
     uses: actions/setup-go@v3
     with:
      go-version: "1.22"

   - name: Extract version from tag
     id: version
     run: |
      echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

   - name: Print version
     run: |
      echo $VERSION
      echo $GITHUB_REF_NAME
      echo ${{ env.VERSION }}

   - name: Build Windows executable
     run: go build -ldflags="-s -w -X main.currentVersion=$VERSION" -o CsvParser.exe

   - name: Create zip archive
     run: Compress-Archive -Path CsvParser.exe, config_example.yml -DestinationPath CsvParser.zip

   - name: Upload Executable to Release
     uses: svenstaro/upload-release-action@v2
     with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      file: CsvParser.zip
      tag: ${{ github.ref }}
