name: Build and Zip Go App (Windows)

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: windows-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Go
     uses: actions/setup-go@v3
     with:
      go-version: "1.21"

   - name: Build Windows executable
     run: go build -o CsvParser.exe

   - name: Create zip archive
     run: Compress-Archive -Path CsvParser.exe, config_UPS.yml -DestinationPath CsvParser.zip

   - name: Upload artifact
     uses: actions/upload-artifact@v3
     with:
      name: CsvParser
      path: CsvParser.zip

   - name: Create a Release
     uses: elgohr/Github-Release-Action@v5
     env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      title: CsvParser Release

   - name: Release
     uses: softprops/action-gh-release@v2
