name: Build and Zip Go App (Windows)

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: windows-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Go
     uses: actions/setup-go@v3
     with:
      go-version: "1.21"

   - name: Build Windows executable
     run: go build -o CsvParser.exe

   - name: Create zip archive
     run: Compress-Archive -Path CsvParser.exe, config_UPS.yml -DestinationPath CsvParser.zip

   - name: Upload artifact
     uses: actions/upload-artifact@v3
     with:
      name: CsvParser
      path: CsvParser.zip

   - name: Create Git tag
     id: tag_creation
     run: |
      git tag v0.0.${{ github.run_number }}
      git push origin $TAG_NAME
      echo "::set-output name=TAG_NAME::v0.0.${{ github.run_number }}"

   - name: Create a Release
     uses: elgohr/Github-Release-Action@v5
     env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      title: CsvParser Release
      tag: ${{ steps.tag_creation.outputs.TAG_NAME }}

   - name: Release
     uses: softprops/action-gh-release@v2
     if: startsWith(github.ref, 'refs/tags/')
     with:
      files: CsvParser.zip
      tag_name: ${{ steps.tag_creation.outputs.TAG_NAME }}
