name: Build and Zip Go App (Windows)

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
 build:
  runs-on: windows-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Go
     uses: actions/setup-go@v3
     with:
      go-version: "1.22"

   - name: Build Windows executable
     run: go build -o CsvParser.exe

   - name: Create zip archive
     run: Compress-Archive -Path CsvParser.exe, config_UPS.yml -DestinationPath bin/CsvParser.zip

   - name: Upload Executable to Release
     uses: svenstaro/upload-release-action@v2
     with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: bin/CsvParser.zip
       tag: ${{ github.ref }}
